### ISSUE TITLE
Include tool-list.yml in release files

### ISSUE THREAD

**Issue by innovate-invent** [phac-nml/irida-plugin-sistr#2]
It would significantly aid deployment if you can include a tool-list.yml compatible with ephemeris in the release files.

**Comment by kbessonov1984** [comment]
Yes, sure. I will specify those dependencies for faster install in the `tool-list.yml` file and attach it to release. I also specified all tool dependencies and versions in README.md at https://github.com/phac-nml/irida-plugin-sistr#galaxy-configuration. Thank you for suggestion

**Comment by kbessonov1984** [comment]
Had updated release `v1.1.1b`  and included `tools-list.yaml` for easier deployment of the plugin and installation of Galaxy required dependencies via `install_tool_shed_tools.py` admin script

**Comment by innovate-invent** [comment]
thank you!
