### ISSUE TITLE
Version 1.0.2

### ISSUE THREAD

**Issue by ajkarloss** [phac-nml/irida-plugin-sistr#4]
Hi, Possible to see the version 1.0.2 codes? I am trying to create the "Sistr" result tab in sistr output.

**Comment by apetkau** [comment]
Version `1.0.2` of SISTR is packaged in the IRIDA codebase (with version number `0.3.0` for the full pipeline).

* Galaxy workflow file/workflow XML: https://github.com/phac-nml/irida/tree/21.05.1/src/main/resources/ca/corefacility/bioinformatics/irida/model/workflow/analysis/type/workflows/SISTRTyping/0.3
* SISTR metadata updater: https://github.com/phac-nml/irida/blob/21.05.1/src/main/java/ca/corefacility/bioinformatics/irida/pipeline/results/updater/impl/SISTRSampleUpdater.java
